### ISSUE TITLE
These may occur performance problem

### ISSUE THREAD

**Issue by DevXiaolan** [TingYinHelen/word-number#1]
https://github.com/TingYinHelen/word-number/blob/35e499002744cb6976f35c985908be2408c456f3/src/index.js#L5

**Comment by DevXiaolan** [comment]
better way:
`Array.prototype.find`

best way:

build two `Map` first

**Comment by DevXiaolan** [comment]
```
Node version: v15.12.0
use fucking reduce     14468938 ops     🐌 
use find               154294769 ops    🐌 🐌 🐌 
use Map                798434241 ops    🐌 🐌 🐌 🐌 🐌 🐌 🐌 🐌 🐌 🐌 🐌 🐌 🐌 🐌 🐌 🐌 🐌 🐌 🐌 🐌 
```

**Comment by TingYinHelen** [comment]
牛逼

**Comment by DevXiaolan** [comment]
The bench case is here  
https://github.com/DevXiaolan/many-bench/blob/master/bench-for-word-number/main.js

glad to left a star ⭐️

**Comment by TingYinHelen** [comment]
![4441616651149_ pic](https://user-images.githubusercontent.com/14006826/112425100-76910080-8d70-11eb-83e4-b8da0c4ad41a.jpg)

**Comment by DevXiaolan** [comment]
the maintainer is too BUSY , so I closed this issue 🤔
